const api =[
    {
        num:0,
        name:"首页",
        currentName:"one"
    },{
        num:1,
        name:"菜谱大全",
        currentName:"two"
    },{
        num:2,
        name:"家常菜谱",
        currentName:"three"
    },{
        num:3,
        name:"美食问答",
        currentName:"four"
    },{
        num:4,
        name:"食谱分类",
        currentName:"five"
    },{
        num:5,
        name:"健康食疗",
        currentName:"six"
    },{
        num:6,
        name:"厨友排行",
        currentName:"seven"
    },{
        num:7,
        name:"用户搜索",
        currentName:"eight"
    },{
        num:8,
        name:"公告",
        currentName:"nine"
    }
]
export default api